services:
  api-gateway-container:
    build:
      context: ..
      dockerfile: api-gateway/Dockerfile
      args:
        PROJECT_VERSION: 0.1.0
        ENVIRONMENT: dev
    image: api-gateway-ecommerce:0.1.0
    ports:
      - "8080:8080"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - zipkin

  user-service-container:
    build:
      context: ..
      dockerfile: user-service/Dockerfile
      args:
        PROJECT_VERSION: 0.1.0
        ENVIRONMENT: dev
    image: user-service-ecommerce:0.1.0
    ports:
      - "8700:8700"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - zipkin

  product-service-container:
    build:
      context: ..
      dockerfile: product-service/Dockerfile
      args:
        PROJECT_VERSION: 0.1.0
        ENVIRONMENT: dev
    image: product-service-ecommerce:0.1.0
    ports:
      - "8500:8500"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - zipkin

  order-service-container:
    build:
      context: ..
      dockerfile: order-service/Dockerfile
      args:
        PROJECT_VERSION: 0.1.0
        ENVIRONMENT: dev
    image: order-service-ecommerce:0.1.0
    ports:
      - "8300:8300"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - zipkin

  payment-service-container:
    build:
      context: ..
      dockerfile: payment-service/Dockerfile
      args:
        PROJECT_VERSION: 0.1.0
        ENVIRONMENT: dev
    image: payment-service-ecommerce:0.1.0
    ports:
      - "8400:8400"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - zipkin

  favourite-service-container:
    build:
      context: ..
      dockerfile: favourite-service/Dockerfile
      args:
        PROJECT_VERSION: 0.1.0
        ENVIRONMENT: dev
    image: favourite-service-ecommerce:0.1.0
    ports:
      - "8800:8800"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - zipkin

  shipping-service-container:
    build:
      context: ..
      dockerfile: shipping-service/Dockerfile
      args:
        PROJECT_VERSION: 0.1.0
        ENVIRONMENT: dev
    image: shipping-service-ecommerce:0.1.0
    ports:
      - "8600:8600"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - zipkin

  proxy-client-container:
    build:
      context: ..
      dockerfile: proxy-client/Dockerfile
      args:
        PROJECT_VERSION: 0.1.0
        ENVIRONMENT: dev
    image: proxy-client-ecommerce:0.1.0
    ports:
      - "8900:8900"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - zipkin

networks:
  microservices_network:
    name: microservices_network
    external: true
